# Generated by Django 2.1.2 on 2019-04-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_dien', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='store',
            new_name='branch',
        ),
    ]
