# Generated by Django 2.1.2 on 2019-04-05 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_dien', '0003_auto_20190402_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_deal',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_created', to=settings.AUTH_USER_MODEL, verbose_name='Thành viên'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history_deal',
            name='tyles',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nhập kho'), (1, 'Xuất cấp'), (2, 'Bán'), (3, 'Chuyển trả')], verbose_name='Chọn loại giao dịch'),
        ),
    ]
